### ISSUE TITLE
How to fix the issue: init_fs_encoding: failed to get the Python codec of the filesystem encoding

### ISSUE THREAD

**Issue by zydjohnHotmail** [pythonnet/codecs#3]
Hello:
I want to play a MP4 format video in Windows 10 PC with Pythonnet.
I have installed Python 3.9.7, but I didn't set up PYTHONPATH and PYTHONHOME, as many people said that they are not necessary.
I installed Pythonnet nuget package:
PM> Install-Package pythonnet -Version 3.0.0-preview2022-03-03
The following is my code:
using Python.Runtime;

namespace PyReturnTransit1Result
{
    class Program
    {
        public const string MP4_File1 = "D:/Videos/1.mp4";
        public static void Python_Play_Video()
        {
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                dynamic cv2 = Py.Import("cv2");
                dynamic cap = cv2.VideoCapture(MP4_File1);
                while (cap.isOpened())
                {
                    var video_frame = cap.read();
                    cv2.imshow("frame", video_frame);
                }
                cap.release();
                cv2.destroyAllWindows();
            }
        }

        static void Main()
        {
            Python_Play_Video();
        }
    }
}
But when I run the above code, I got errors:
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\SoccerVideos\\PythonNet\\PyReturnTransit1Result\\PyReturnTransit1Result\\bin\\x64\\Debug\\net5.0\\PyReturnTransit1Result.exe'
  sys.base_prefix = 'C:\\Program Files\\Python39'
  sys.base_exec_prefix = 'C:\\Program Files\\Python39'
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\SoccerVideos\\PythonNet\\PyReturnTransit1Result\\PyReturnTransit1Result\\bin\\x64\\Debug\\net5.0\\PyReturnTransit1Result.exe'
  sys.prefix = 'C:\\Program Files\\Python39'
  sys.exec_prefix = 'C:\\Program Files\\Python39'
  sys.path = [
    'C:\\Program Files\\Python39\\python39.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\SoccerVideos\\PythonNet\\PyReturnTransit1Result\\PyReturnTransit1Result\\bin\\x64\\Debug\\net5.0',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00009094 (most recent call first):
<no Python frame>

C:\SoccerVideos\PythonNet\PyReturnTransit1Result\PyReturnTransit1Result\bin\x64\Debug\net5.0\PyReturnTransit1Result.exe (process 34764) exited with code 1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
The similar code in Python works in my PC.
Any suggestion on how I can fix this issue?
Thanks,

**Comment by lostmsu** [comment]
This is a problem with your Python environment configuration, not with Python.NET

**Comment by zydjohnHotmail** [comment]
Hello:
As I am confused, could you please indicate what exactly is the environment configuration issue?
thanks,

**Comment by lostmsu** [comment]
This is a bug tracker, not a support forum.
